# Site settings
title: christopher chow
description: My personal website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: christopher chow
user_description: trading, python, R
user_title: trading, python, R
twitter_username: mortensorensen
github_username: acemagi
linkedin: chowchristopher

# Google-analytics
google-analytics:
  id: "G-9BSCJGV40L"

exclude: ["package.json", "src", "node_modules"]
