# Site settings
title: morten.lol
description: My personal website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: morten sorensen
user_description: kdb+, C++, algorithmic trading
user_title: kdb+, C++, algorithmic trading
twitter_username: mortensorensen
github_username: mortensorensen
linkedin: mortensoerensen

# Google-analytics
google-analytics:
  id: "G-9BSCJGV40L"

exclude: ["package.json", "src", "node_modules"]
